### ISSUE TITLE
mybot.py issue

### ISSUE THREAD

**Issue by Omtrw** [fnk93/Summoners-War-Bot#12]
File "mybot.py", line 24
    with open('config.json', 'r') as f:
                                      ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by SpellCraft** [comment]
You can fix this by re-tabbing the line back to where it's supposed to be. Sometimes Windows and other programs (like VSCode) mess with Pythons indendations even if it looks right.

**Comment by fnk93** [comment]
It was actually line 23 and 22 which was wrong.

**Comment by Omtrw** [comment]
kk ty

**Comment by Omtrw** [comment]
new issue : 
File "mybot.py", line 1112
    self.bot.GetArenaLog()
                         ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by fnk93** [comment]
Same Error, fixed it. Need to stop making changes on the files on the go without a proper editor :D

**Comment by Omtrw** [comment]
haha ty :)
