### ISSUE TITLE
Pycrypto vs Pycryptodome

### ISSUE THREAD

**Issue by SpellCraft** [fnk93/Summoners-War-Bot#17]
Any plans on moving away from the discontinued pycrypto and move over to pycryptodome instead?

Currently trying to run this on my Work machine and running the latest version of W10/Py3 I absolutely cannot get pycrypto to install without hacking it in.

**Comment by FR96** [comment]
Pretty sure that you can install pycryptodome and it'll work, in fact I think i have installed it that way. 
You access the library the same way 'from crypto.' etc.

**Comment by SpellCraft** [comment]
Hmm, weird. I tried installing pycryptodome and I just kept getting
messages where the Crypto module couldn't be found.

**Comment by fnk93** [comment]
Exactly. Pycrytodome is used just like Pycrypto but works for Python 3. I also installed pycryptodome on my machine.
In your case search for the folder "crypto" in your python/lib/site-packages (either in your global Python 3 folder or your virtual environment) then rename it to "Crypto". Seems to be a common issue where the first letter isn't capitalized.
