### ISSUE TITLE
OTP update

### ISSUE THREAD

**Issue by oddessax** [fnk93/Summoners-War-Bot#23]
Hey mate, are you going to covert & merge the OPT code into your update? was going to try and work it out but thought i'd check if you're already looking at it. Mila432 has released the patch but I'm using your python3 variation.

**Comment by fnk93** [comment]
Will be converting it today.

**Comment by l2avenholm** [comment]
@oddessax Have you figured out the issue? Can't make it work with OTP.

I have the same issue that response from https://hub.qpyou.cn/otp/login request doesn't have Location header.

**Comment by oddessax** [comment]
Nope @l2avenholm can't work it out; @fnk93 any chance of the latest changes being implimented into your p3 variation?

**Comment by fnk93** [comment]
@oddessax @l2avenholm OTP update from mila included now. Nonetheless, there seem to be more request-values now. Need to look into it.
